import { Geist, Geist_Mono, Fraunces } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/components/ThemeProvider';
import { ContactModalProvider } from '@/context/ContactModalContext';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import Script from 'next/script';
import AnalyticsTracker from '@/components/AnalyticsTracker';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const heading = Fraunces({
  variable: '--font-heading',
  subsets: ['latin'],
  weight: ['500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Phelan Focus',
  description: 'Generated by create next app',
};

const gaID = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Scripts */}
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${gaID}`}
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${gaID}', {
      page_path: window.location.pathname,
    });
  `}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${heading.variable} antialiased`}>
        <AnalyticsTracker />
        <ThemeProvider>
          <ContactModalProvider>{children}</ContactModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
