import { Geist, Fraunces } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/components/ThemeProvider';
import { ContactModalProvider } from '@/context/ContactModalContext';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import Script from 'next/script';
import AnalyticsTracker from '@/components/AnalyticsTracker';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const heading = Fraunces({
  variable: '--font-heading',
  subsets: ['latin'],
  weight: ['500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Phelan Focus',
  description: 'Generated by create next app',
};

const gaID = process.env.NEXT_PUBLIC_GA_ID;
// Only load Google Analytics when a real measurement ID is configured.
// Otherwise the ~140KB gtag script loads on every page for nothing.
const gaEnabled = !!gaID && gaID !== 'G-PLACEHOLDER';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Scripts */}
        {gaEnabled && (
          <>
            <Script
              strategy="afterInteractive"
              src={`https://www.googletagmanager.com/gtag/js?id=${gaID}`}
            />
            <Script id="ga-init" strategy="afterInteractive">
              {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${gaID}', {
      page_path: window.location.pathname,
    });
  `}
            </Script>
          </>
        )}
      </head>
      <body className={`${geistSans.variable} ${heading.variable} antialiased`}>
        <AnalyticsTracker />
        <ThemeProvider>
          <ContactModalProvider>{children}</ContactModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
